security:
    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN: [ROLE_MODERATOR, ROLE_MANAGE_ARTICLES, ROLE_ALLOWED_TO_SWITCH]
        ROLE_MODERATOR: [ROLE_MANAGE_ARTICLES, ROLE_ALLOWED_TO_SWITCH]
        ROLE_EDITOR: [ROLE_MANAGE_ARTICLES]
    providers:
        our_users:
            entity: { class: AppBundle\Entity\User, property: email }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                  - app.security.login_form_authenticator
            logout:
                path: /logout

            switch_user: ~
    access_control:
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_MODERATOR] }
        - { path: ^/settings/, role: ROLE_USER }
        - { path: ^/article/new, role: ROLE_USER }