parameters:
    riot_api.guzzle_client.class: AppBundle\Controller\Classes\GuzzleHttpClient
    riot_api.service_champion.class: AppBundle\Controller\Service\ChampionService

services:
    riot_api.guzzle_client:
        class: "%riot_api.guzzle_client.class%"
        arguments: ['@service_container']

    riot_api.service_champion:
        class: "%riot_api.service_champion.class%"
        arguments: ['@riot_api.guzzle_client','@service_container', '@champion.repository']

    AppBundle\Controller\HomepageController:
        arguments: ["@riot_api.service_champion"]

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{entities,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'
    app.security.login_form_authenticator:
            class: AppBundle\Controller\Security\LoginFormAuthenticator
            autowire: true
    app.doctrine.hash_password_listener:
            class: AppBundle\Doctrine\HashPasswordListener
            autowire: true
            tags:
              - { name: doctrine.event_subscriber }

    AppBundle\Repository\CommentRepository:
      class: AppBundle\Repository\CommentRepository
      factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
      arguments:
        - AppBundle\Entity\Comment

    AppBundle\Repository\VerificationRepository:
          class: AppBundle\Repository\VerificationRepository
          factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
          arguments:
            - AppBundle\Entity\Verification

    champion.repository:
      class: AppBundle\Repository\ChampionRepository
      factory: ['@doctrine.orm.entity_manager', getRepository]
      arguments:
          - AppBundle\Entity\Champion
