parameters:
    riot_api.guzzle_client.class: AppBundle\Controller\Classes\GuzzleHttpClient
    riot_api.service_champion.class: ChampionBundle\Model\Repository\ChampionRepository

services:
    riot_api.guzzle_client:
        class: "%riot_api.guzzle_client.class%"
        arguments: ['@service_container']

    riot_api.service_champion:
        class: "%riot_api.service_champion.class%"
        arguments: ['@riot_api.guzzle_client','@service_container', '@champion.repository']

    AppBundle\Controller\HomepageController:
        arguments: ["@riot_api.service_champion"]

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{entities,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    ChampionBundle\:
        resource: '../../src/ChampionBundle/*'
        exclude: '../../src/ChampionBundle/Model/{Entity}'

    ChampionBundle\Controller\:
        resource: '../../src/ChampionBundle/Controller'
        tags: ['controller.service_arguments']

    FindSummonerBundle\:
        resource: '../../src/FindSummonerBundle/*'
        exclude: '../../src/FindSummonerBundle/Model/{Entity}'

    FindSummonerBundle\Controller\:
        resource: '../../src/FindSummonerBundle/Controller'
        tags: ['controller.service_arguments']

    AppBundle\Repository\CommentRepository:
      class: AppBundle\Repository\CommentRepository
      factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
      arguments:
        - AppBundle\Entity\Comment

    AppBundle\Repository\VerificationRepository:
      class: AppBundle\Repository\VerificationRepository
      factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
      arguments:
        - AppBundle\Entity\Verification

    ChampionBundle\Model\Repository\ChampionRepository:
      class: ChampionBundle\Model\Repository\ChampionRepository
      factory: ['@doctrine.orm.entity_manager', getRepository]
      arguments:
          - ChampionBundle\Model\Entity\Champion

    AppBundle\Repository\SummonerRepository:
      class: AppBundle\Repository\SummonerRepository
      factory: ['@doctrine.orm.entity_manager', getRepository]
      arguments:
          - AppBundle\Entity\Summoner

    FindSummonerBundle\Model\Repository\MasteryRepository:
      class: FindSummonerBundle\Model\Repository\MasteryRepository
      factory: ['@doctrine.orm.entity_manager', getRepository]
      arguments:
          - FindSummonerBundle\Model\Entity\Mastery