easy_admin:
    entities:
        User:
            class: AppBundle\Entity\User
            label: 'Users'
            password_encoding: { algorithm: 'bcrypt'}
            show:
                fields:
                    - 'id'
                    - 'email'
                    - 'roles'
            list:
                sort: ['lastLogin', 'DESC']
                title: '%%entity_label%% list'
                fields:
                    - 'id'
                    - 'email'
                    - 'username'
                    - 'roles'
                    - 'enabled'
                    - 'lastLogin'
            edit:
                title: '%%entity_label%% list'
                fields:
                    - 'email'
                    - 'username'
                    - 'username_canonical'
                    - 'roles'
                    - 'lastLogin'