easy_admin:
    entities:
        User:
            class: AppBundle\Entity\User
            label: 'Users'
            password_encoding: { algorithm: 'bcrypt'}
            show:
                fields:
                    - 'id'
                    - 'email'
                    - 'roles'
            list:
                title: '%%entity_label%% list'
                fields:
                    - 'id'
                    - 'email'
                    - 'nickname'
                    - 'roles'
            edit:
                title: '%%entity_label%% list'
                fields:
                    - 'email'
                    - 'email'
                    - 'nickname'
                    - 'roles'