easy_admin:
    entities:
        Version:
            class: AppBundle\Entity\Timer
            label: 'Info'
            disabled_actions: ['new', 'delete']
            show:
                fields:
                    - 'version'
                    - 'timestamp'
            list:
                title: 'Last update information'
                fields:
                    - 'version'
                    - { property: 'timestamp', type: datetime }